import type { KnipConfig } from "knip";

const config: KnipConfig = {
	entry: [
		"src/client.tsx",
		"src/ssr.tsx", 
		"src/router.tsx",
		"src/routes/**/*.tsx",
		"src/api.ts",
		"app.config.ts",
		"src/lib/utils.ts", // Utility functions (cn, clsx, twMerge)
	],
	project: ["src/**/*.{ts,tsx}", "app.config.ts"],
	ignore: [
		"src/routeTree.gen.ts", // Auto-generated by TanStack Router
		"**/*.test.{ts,tsx}",
		"**/*.spec.{ts,tsx}",
	],
	ignoreExportsUsedInFile: true,
	ignoreDependencies: [
		// Core framework dependencies used by build system
		"@tanstack/router-plugin",
		// Testing utilities 
		"@testing-library/dom",
		"@testing-library/react", 
		"web-vitals",
		// Build tools
		"@vitejs/plugin-react",
		// CSS/Styling tools
		"tailwindcss", // Used by build system
		"tailwindcss-animate", // CSS animations
		// Utility libraries kept for future use
		"class-variance-authority", // CVA for component variants
		// Development tools
		"@tanstack/react-query-devtools", // Used conditionally in dev
	],
};

export default config;