/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TrackerImport } from './routes/tracker'
import { Route as RetrospectiveImport } from './routes/retrospective'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TrackerRoute = TrackerImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRoute,
} as any)

const RetrospectiveRoute = RetrospectiveImport.update({
  id: '/retrospective',
  path: '/retrospective',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/retrospective': {
      id: '/retrospective'
      path: '/retrospective'
      fullPath: '/retrospective'
      preLoaderRoute: typeof RetrospectiveImport
      parentRoute: typeof rootRoute
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/retrospective': typeof RetrospectiveRoute
  '/tracker': typeof TrackerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/retrospective': typeof RetrospectiveRoute
  '/tracker': typeof TrackerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/retrospective': typeof RetrospectiveRoute
  '/tracker': typeof TrackerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/retrospective' | '/tracker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/retrospective' | '/tracker'
  id: '__root__' | '/' | '/retrospective' | '/tracker'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RetrospectiveRoute: typeof RetrospectiveRoute
  TrackerRoute: typeof TrackerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RetrospectiveRoute: RetrospectiveRoute,
  TrackerRoute: TrackerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/retrospective",
        "/tracker"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/retrospective": {
      "filePath": "retrospective.tsx"
    },
    "/tracker": {
      "filePath": "tracker.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
